import { writable } from "svelte/store";
export const INVENTORY = writable([
    {
      materialName: "Nails",
      unit: "kg",
      materialdescription: "High-quality steel nails for construction.",
      brand: "NailPro",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Hammer",
      unit: "pc",
      materialdescription: "Durable claw hammer with a comfortable grip.",
      brand: "HammerKing",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Measuring Tape",
      unit: "meter",
      materialdescription: "Retractable measuring tape with a lock feature.",
      brand: "MeasureMaster",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Screwdriver",
      unit: "pc",
      materialdescription: "Multi-bit screwdriver for various screws.",
      brand: "ScrewTight",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Wood Glue",
      unit: "liters",
      materialdescription: "Strong adhesive for woodworking projects.",
      brand: "GluePro",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Pliers",
      unit: "pc",
      materialdescription: "Heavy-duty pliers for gripping and cutting.",
      brand: "GripStrong",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Sandpaper",
      unit: "pc",
      materialdescription: "Assorted grit sandpaper for smoothing surfaces.",
      brand: "SmoothFinish",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Drill Bits",
      unit: "pc",
      materialdescription: "Set of high-speed steel drill bits.",
      brand: "DrillMaster",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Paint Brush",
      unit: "pc",
      materialdescription: "High-quality paint brush for smooth application.",
      brand: "BrushPerfect",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Wrench Set",
      unit: "pc",
      materialdescription: "Set of adjustable wrenches for various sizes.",
      brand: "TightFit",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Utility Knife",
      unit: "pc",
      materialdescription: "Sharp utility knife with retractable blade.",
      brand: "KnifeEdge",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Level",
      unit: "pc",
      materialdescription: "Precision level for accurate measurements.",
      brand: "LevelLine",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Screws",
      unit: "kg",
      materialdescription: "Assorted screws for various applications.",
      brand: "ScrewMaster",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Caulking Gun",
      unit: "pc",
      materialdescription: "Heavy-duty caulking gun for sealants.",
      brand: "SealPro",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Tape Measure",
      unit: "meter",
      materialdescription: "Durable tape measure with easy-read markings.",
      brand: "MeasureRight",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Saw",
      unit: "pc",
      materialdescription: "Sharp hand saw for cutting wood.",
      brand: "CutSharp",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Bolt Cutter",
      unit: "pc",
      materialdescription: "Powerful bolt cutter for tough materials.",
      brand: "BoltBreak",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Chisel Set",
      unit: "pc",
      materialdescription: "Set of wood chisels for carving and shaping.",
      brand: "ChiselCraft",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Workbench",
      unit: "pc",
      materialdescription: "Sturdy workbench with storage shelves.",
      brand: "BenchPro",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Safety Glasses",
      unit: "pc",
      materialdescription: "Protective eyewear for workshop safety.",
      brand: "SafeVision",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Socket Set",
      unit: "pc",
      materialdescription: "Complete set of sockets for various bolts.",
      brand: "SocketMaster",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Tool Box",
      unit: "pc",
      materialdescription: "Portable tool box with multiple compartments.",
      brand: "ToolSafe",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Work Gloves",
      unit: "pc",
      materialdescription: "Durable gloves for hand protection.",
      brand: "HandGuard",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Drill",
      unit: "pc",
      materialdescription: "Cordless drill with variable speed settings.",
      brand: "DrillPro",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Tape",
      unit: "meter",
      materialdescription: "Strong adhesive tape for various uses.",
      brand: "TapeStick",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Ladder",
      unit: "pc",
      materialdescription: "Foldable ladder for reaching high places.",
      brand: "StepUp",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Flashlight",
      unit: "pc",
      materialdescription: "High-intensity flashlight for dark areas.",
      brand: "BrightBeam",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Hex Keys",
      unit: "pc",
      materialdescription: "Set of hex keys for hexagonal bolts.",
      brand: "HexMaster",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Wire Cutter",
      unit: "pc",
      materialdescription: "Sharp wire cutter for clean cuts.",
      brand: "WireSharp",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    },
    {
      materialName: "Sledgehammer",
      unit: "pc",
      materialdescription: "Heavy-duty sledgehammer for demolition.",
      brand: "HammerForce",
  
      date:"08/17/24",
      materialCode: "K1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1000,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "remark",
    }
  ]);