import { writable } from "svelte/store";
export const INVENTORY = writable([
    {
      materialName: "Nails",
      unit: "kg",
      materialdescription: "High-quality steel nails for construction.",
      brand: "NailPro",
  
      date:"08/18/24",
      materialCode: "P1237",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1011,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "pending",
    },
    {
      materialName: "Hammer",
      unit: "pc",
      materialdescription: "Durable claw hammer with a comfortable grip.",
      brand: "HammerKing",
  
      date:"08/15/24",
      materialCode: "P1238",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 850,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "pending",
    },
    {
      materialName: "Measuring Tape",
      unit: "meter",
      materialdescription: "Retractable measuring tape with a lock feature.",
      brand: "MeasureMaster",
  
      date:"08/15/24",
      materialCode: "P1239",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 950,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "pending",
    },
    {
      materialName: "Screwdriver",
      unit: "pc",
      materialdescription: "Multi-bit screwdriver for various screws.",
      brand: "ScrewTight",
  
      date:"08/15/24",
      materialCode: "P1241",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 540,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "pending",
    },
    {
      materialName: "Wood Glue",
      unit: "liters",
      materialdescription: "Strong adhesive for woodworking projects.",
      brand: "GluePro",
  
      date:"08/15/24",
      materialCode: "P1242",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1016,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "pending",
    },
    {
      materialName: "Pliers",
      unit: "pc",
      materialdescription: "Heavy-duty pliers for gripping and cutting.",
      brand: "GripStrong",
  
      date:"08/15/24",
      materialCode: "P1243",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 350,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "pending",
    },
    {
      materialName: "Sandpaper",
      unit: "pc",
      materialdescription: "Assorted grit sandpaper for smoothing surfaces.",
      brand: "SmoothFinish",
  
      date:"08/15/24",
      materialCode: "P1244",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 200,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "pending",
    },
    {
      materialName: "Drill Bits",
      unit: "pc",
      materialdescription: "Set of high-speed steel drill bits.",
      brand: "DrillMaster",
  
      date:"08/15/24",
      materialCode: "P1245",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 190,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "pending",
    },
    {
      materialName: "Paint Brush",
      unit: "pc",
      materialdescription: "High-quality paint brush for smooth application.",
      brand: "BrushPerfect",
  
      date:"08/15/24",
      materialCode: "L1243",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1021,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "for checking",
    },
    {
      materialName: "Wrench Set",
      unit: "pc",
      materialdescription: "Set of adjustable wrenches for various sizes.",
      brand: "TightFit",
  
      date:"08/15/24",
      materialCode: "L1244",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 400,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "for checking",
    },
    {
      materialName: "Utility Knife",
      unit: "pc",
      materialdescription: "Sharp utility knife with retractable blade.",
      brand: "KnifeEdge",
  
      date:"08/15/24",
      materialCode: "L1245",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1024,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "for checking",
    },
    {
      materialName: "Level",
      unit: "pc",
      materialdescription: "Precision level for accurate measurements.",
      brand: "LevelLine",
  
      date:"08/15/24",
      materialCode: "L1246",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 800,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "for checking",
    },
    {
      materialName: "Screws",
      unit: "kg",
      materialdescription: "Assorted screws for various applications.",
      brand: "ScrewMaster",
  
      date:"08/19/24",
      materialCode: "L1247",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 780,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "for checking",
    },
    {
      materialName: "Caulking Gun",
      unit: "pc",
      materialdescription: "Heavy-duty caulking gun for sealants.",
      brand: "SealPro",
  
      date:"08/19/24",
      materialCode: "L1248",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 730,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "for checking",
    },
    {
      materialName: "Tape Measure",
      unit: "meter",
      materialdescription: "Durable tape measure with easy-read markings.",
      brand: "MeasureRight",
  
      date:"08/19/24",
      materialCode: "L1249",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 860,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "for checking",
    },
    {
      materialName: "Saw",
      unit: "pc",
      materialdescription: "Sharp hand saw for cutting wood.",
      brand: "CutSharp",
  
      date:"08/19/24",
      materialCode: "M1251",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 680,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "for checking",
    },
    {
      materialName: "Bolt Cutter",
      unit: "pc",
      materialdescription: "Powerful bolt cutter for tough materials.",
      brand: "BoltBreak",
  
      date:"08/19/24",
      materialCode: "M1252",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1031,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "for checking",
    },
    {
      materialName: "Chisel Set",
      unit: "pc",
      materialdescription: "Set of wood chisels for carving and shaping.",
      brand: "ChiselCraft",
  
      date:"08/19/24",
      materialCode: "M1253",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1032,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "ok",
    },
    {
      materialName: "Workbench",
      unit: "pc",
      materialdescription: "Sturdy workbench with storage shelves.",
      brand: "BenchPro",
  
      date:"08/20/24",
      materialCode: "M1254",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1033,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "ok",
    },
    {
      materialName: "Safety Glasses",
      unit: "pc",
      materialdescription: "Protective eyewear for workshop safety.",
      brand: "SafeVision",
  
      date:"08/20/24",
      materialCode: "M1255",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1034,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "ok",
    },
    {
      materialName: "Socket Set",
      unit: "pc",
      materialdescription: "Complete set of sockets for various bolts.",
      brand: "SocketMaster",
  
      date:"08/20/24",
      materialCode: "M1256",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1035,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "ok",
    },
    {
      materialName: "Tool Box",
      unit: "pc",
      materialdescription: "Portable tool box with multiple compartments.",
      brand: "ToolSafe",
  
      date:"08/21/24",
      materialCode: "M1257",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1036,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "ok",
    },
    {
      materialName: "Work Gloves",
      unit: "pc",
      materialdescription: "Durable gloves for hand protection.",
      brand: "HandGuard",
  
      date:"08/21/24",
      materialCode: "M1258",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1037,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "ok",
    },
    {
      materialName: "Drill",
      unit: "pc",
      materialdescription: "Cordless drill with variable speed settings.",
      brand: "DrillPro",
  
      date:"08/21/24",
      materialCode: "M1259",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1038,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "ok",
    },
    {
      materialName: "Tape",
      unit: "meter",
      materialdescription: "Strong adhesive tape for various uses.",
      brand: "TapeStick",
  
      date:"08/21/24",
      materialCode: "M1250",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1039,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "arrive",
    },
    {
      materialName: "Ladder",
      unit: "pc",
      materialdescription: "Foldable ladder for reaching high places.",
      brand: "StepUp",
  
      date:"08/21/24",
      materialCode: "M1252",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1001,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "arrive",
    },
    {
      materialName: "Flashlight",
      unit: "pc",
      materialdescription: "High-intensity flashlight for dark areas.",
      brand: "BrightBeam",
  
      date:"08/22/24",
      materialCode: "M1262",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 1002,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "arrive",
    },
    {
      materialName: "Hex Keys",
      unit: "pc",
      materialdescription: "Set of hex keys for hexagonal bolts.",
      brand: "HexMaster",
  
      date:"08/22/24",
      materialCode: "P1234",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 800,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "arrive",
    },
    {
      materialName: "Wire Cutter",
      unit: "pc",
      materialdescription: "Sharp wire cutter for clean cuts.",
      brand: "WireSharp",
  
      date:"08/2./24",
      materialCode: "P1235",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 700,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "arrive",
    },
    {
      materialName: "Sledgehammer",
      unit: "pc",
      materialdescription: "Heavy-duty sledgehammer for demolition.",
      brand: "HammerForce",
  
      date:"08/23/24",
      materialCode: "P1236",
      availablematerial: 1000,
      stockin: 2000,
      stockout: 500,
      purchaseqty: 3000,
      pendingQty: 500,
      purchaseNumber: "P12345",
      vendor: "dummy - Inc company",
     vendorPhonenumber: +63123456781,
      vendorTelephone: "+111 222 333",
      vendorEmail: "dummy@email",
      vendorAddress: "Mariveles Bataan",
      vendeorBankAcc: "123 456 678",
      unitprice: "number",
      totalPrice: "amountmoney",
      datePurchase: "date",
      deliverDate: "date",
      etaDate: "date",
      arrivalDate: "date",
      status: "arrive",
    }
  ]);